apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-job
  annotations:
    argocd.argoproj.io/hook: Sync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: playwright
    spec:
      containers:
        - name: playwright
          image: your-dockerhub/playwright-tests:latest
          imagePullPolicy: Always
          env:
            - name: TEST_SUITE
              value: "@api"
      restartPolicy: Never